version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    env_file: .env
    ports:
      - $MYSQL_LISTEN_PORT:3306
    volumes:
      - ./mysql/data:$MYSQL_DATA_DIR
      - ./mysql/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: laravel_pma
    env_file: .env
    ports:
      - $PHPMYADMIN_LISTEN_PORT:80
    volumes:
      - ./phpmyadmin/sessions:/var/lib/php7/session
    depends_on:
      - mysql

  apache:
    build: ../public
    env_file: .env
    container_name: laravel_apache
    ports:
      - $APACHE_LISTEN_PORT:80
    volumes:
      - ../public:/var/www/html
      - /var/www/html/vendor
      - ./apache2/sites-available:/etc/apache2/sites-available
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
